# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://gokhansengun.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Gökhan Şengün

# Short description of your site
description: .net teknolojileri, docker, sql ve nosql veri tabanları, performans optimizasyonu, ci/cd ve verimlilik artıran geliştirici araçları ile ilgili yazılar

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  en:
    Blog: "index-en/"
    About Me: "aboutme-en"
    #Arama: "search"
  tr:
    Blog: ""
    Hakkımda: "aboutme"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Gökhan Şengün
  email: "gokhansengun@gmail.com"
  facebook: gokhan.sengun.39  # eg. daattali
  github: gokhansengun    # eg. daattali
  twitter: gokhansengun   # eg. daattali
  linkedin: "in/gökhan-şengün-69786735"  # eg. "pub/dean-attali/8/946/143"
  stackoverflow: "1717349/gökhan-Şengün"  # eg. "3943160/daattali"
 
# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: true
  twitter: true
  github: true
  linkedin: true
  stackoverflow: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "www.gokhansengun.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "gokhansengun"

# Fill in your Google Analytics ID to track your website using GA
# google_analytics: "UA-80691314-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Istanbul"
markdown: kramdown
highlighter: rouge
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# translations

t:
  en:
    next: "NEXT"
    previous: "PREVIOUS"
    level: "Level"
    date: "Date"
    blog_post: "Blog Posts"
    medium_post: "Medium Posts"
  tr:
    next: "SONRAKİ"
    previous: "ÖNCEKİ"
    level: "Seviye"
    date: "Tarih"
    blog_post: "Blog Yazıları"
    medium_post: "Medium  Yazıları"

t_date:
  en:
    January: "Jan"
    February: "Feb"
    March: "Mar"
    April: "Apr"
    May: "May"
    June: "Jun"
    July: "Jul"
    August: "Aug"
    September: "Sep"
    October: "Oct"
    November: "Nov"
    December: "Dec"
  tr:
    January: "Oca"
    February: "Şub"
    March: "Mar"
    April: "Nis"
    May: "May"
    June: "Haz"
    July: "Tem"
    August: "Ağu"
    September: "Eyl"
    October: "Eki"
    November: "Kas"
    December: "Ara"

